### ISSUE TITLE
Vise tilgang til e-ressurs basert på institusjon

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/lsm#10]
For trykte bøker kan vi enkelt hente ut `holdings` for andre institusjoner. For e-bøker er det litt værre… Vi kan kanskje bruke informasjon fra delivery/delcategory. Alle institusjoner med `Alma-E` bør ihvertfall ha en post, men vi vet ikke noe om den er aktiv eller ikke? Vi får vel heller ikke ut URL-en til andres uresolver?

```
      delivery:
            institution:
              - $$VBIBSYS$$OBIBSYS_ILS71497149080002201
              - $$VNTNU_UB$$OBIBSYS_ILS71497149080002201
              - $$VUBO$$OBIBSYS_ILS71497149080002201
              - $$VUBB$$OBIBSYS_ILS71521410480002201
              - $$VUBTO$$OBIBSYS_ILS71521410480002201
              - $$VUBO$$OBIBSYS_ILS71521410480002201
              - $$VFOLKHELS$$OBIBSYS_ILS71521410480002201
              - $$VNTNU_UB$$OBIBSYS_ILS71521410480002201
              - $$VBIBSYS$$OBIBSYS_ILS71521410480002201
            delcategory:
              - $$VAlma-P$$IBIBSYS$$OBIBSYS_ILS71497149080002201
              - $$VAlma-P$$INTNU_UB$$OBIBSYS_ILS71497149080002201
              - $$VAlma-P$$IUBO$$OBIBSYS_ILS71497149080002201
              - $$VAlma-E$$IUBB$$OBIBSYS_ILS71521410480002201
              - $$VAlma-E$$IUBTO$$OBIBSYS_ILS71521410480002201
              - $$VAlma-E$$IUBO$$OBIBSYS_ILS71521410480002201
              - $$VAlma-E$$IFOLKHELS$$OBIBSYS_ILS71521410480002201
              - $$VAlma-E$$INTNU_UB$$OBIBSYS_ILS71521410480002201
              - $$VAlma-P$$IBIBSYS$$OBIBSYS_ILS71521410480002201
```
